spring.application.name=mrManagement
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/db_mitarbeiterverwaltung
spring.datasource.username=sinarox
spring.datasource.password=${SINAROX_DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver